### PR TITLE
Dart to java converted

### PR DESCRIPTION
**Pull request by IamShivamJaiswal**
fix issue #1

### CODE REVIEW

**Comment by abhinavsp0730** [comment]
Hey @IamShivamJaiswal is it sending json response??

**Comment by IamShivamJaiswal** [comment]
Yes but as string, so if you need string in json there's other tools for it

**Comment by im-ankitjais** [comment]
@IamShivamJaiswal can you please tell us which android dependency  of httpclint library  you used?

**Comment by IamShivamJaiswal** [comment]
I have already shared maven repository details for the same

**Comment by im-ankitjais** [comment]
WhatsApp Image 2019-11-01 at 11 45 48 PM

@IamShivamJaiswal  While running your code I am getting this type of error, Any Suggestions?

**Pull request merged**
